name: Publish DevContainer Image to GHCR

on:
  workflow_dispatch:
    inputs:
      devcontainer_choice:
        description: 'DevContainer to build (only those with Dockerfiles)'
        required: true
        type: choice
        options:
          - 'default-container'
          - 'codex-container'
        default: 'default-container'
      image_tag:
        description: 'Image tag (e.g., latest, v1.0.0)'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image name
        id: image-name
        run: |
          case "${{ github.event.inputs.devcontainer_choice }}" in
            "default-container")
              echo "name=default" >> $GITHUB_OUTPUT
              ;;
            "codex-container")
              echo "name=codex" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "name=${{ github.event.inputs.devcontainer_choice }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./.devcontainer/${{ github.event.inputs.devcontainer_choice }}
          file: ./.devcontainer/${{ github.event.inputs.devcontainer_choice }}/Dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository }}/${{ steps.image-name.outputs.name }}:${{ github.event.inputs.image_tag }}
            ghcr.io/${{ github.repository }}/${{ steps.image-name.outputs.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
