name: Publish DevContainer Image to GHCR

on:
  workflow_dispatch:
    inputs:
      devcontainer_choice:
        description: 'DevContainer to build (only those with Dockerfiles)'
        required: true
        type: choice
        options:
          - 'docker'
          - 'codex-docker'
        default: 'docker'
      image_tag:
        description: 'Image tag (e.g., latest, v1.0.0)'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./.devcontainer/${{ github.event.inputs.devcontainer_choice }}
          file: ./.devcontainer/${{ github.event.inputs.devcontainer_choice }}/Dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository }}/devcontainer-${{ github.event.inputs.devcontainer_choice }}:${{ github.event.inputs.image_tag }}
            ghcr.io/${{ github.repository }}/devcontainer-${{ github.event.inputs.devcontainer_choice }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
